### PR TITLE
Update from Phoenix 5 to Phoenix 6

### PR DESCRIPTION
**Pull request by ProfessorAtomicManiac**

### CODE REVIEW

**Comment by ProfessorAtomicManiac** [comment]
Originally we made the decision to update from Phoenix 5 to 6 so that when the CANcoders on the drivetrain are disconnected, the robot will switch to relative encoders. (Not yet tested, will update if updating to Phoenix 6 fixes the issue).

However, Phoenix 6 has a ton of changes, making this PR a very dangerous change. From what I gathered (Please double check that I got everything here correct):
-TalonSRX and VictorSPX is no longer supported. The library only supports TalonFX.
-All motor controllers and encoders support [simulation](https://pro.docs.ctr-electronics.com/en/latest/docs/api-reference/wpilib-integration/motorcontroller-integration.html#simulation) and implement WPILIB's `MotorController` interface. Therefore **all mock classes are no longer necessary and should be removed.** This also means `ErrorCodeAnswer.java` will not be used, so maybe consider also removing it.
-[Nominal output](https://pro.docs.ctr-electronics.com/en/latest/docs/migration/migration-guide/feature-replacements-guide.html) has been removed. In general please double check I did the config for TalonFXs correctedly, since I couldn't find exact matches for some of the options. (Ex: DutyCycle in Phoenix 6 ?= Continuous in Phoenix 5). I also couldn't find where to put in timeouts for some of the functions.
-**CANcoders only return output from [0, 1] or [-0.5, 0.5] in rotations.**

**Comment by CoolSpy3** [comment]
Wow! I did not realize so much had changed. I think we might need to reevaluate what we need to update. In order:
* Can confirm. This might be because Phoenix 6 is actually just public Phoenix Pro and is only made to target CANCoders and FX series products. We might have to compromise and download the combined Phoenix 5/Phoenix 6 version to maintain support for these controllers. If we do axe them, it MUST be a leadership discussion because I know we have a lot of Talon SRXs lying around, and (at the moment) lib199 does not support using Spark Maxes in brushed mode.
* See above for why we might need to keep this, however, I wouldn't put it past CTRE to have fixed any simulation problems by now. We should look into whether this code is still necessary. Also, can you double check that all the necessary endpoints are exposed in their simulation implementation. Also check if they have a gearing function and how that plays with simulation. If they don't have one, we need to implement it. (This is similar to #44) 
* If we aren't using Talon FXs, I wouldn't implement code for them.
* This shouldn't be a problem AFAIK, the only place we use them is one or two lines in `SwerveModule`

**Comment by ProfessorAtomicManiac** [comment]
[2024 update to Phoenix](https://store.ctr-electronics.com/blog/2024-frc-kickoff-phoenix-software-release) allows us to have both Phoenix 5 and Phoenix 6 as dependencies. I would opt for including them both so we can keep our old features while also giving us the ability to use new motors such as the Krakens. The CANCoder class is deprecated and it is recommended to use the v6 version. Phoenix 5 will stay so we don't have to remove the CANCoder classes, but I'd say we should do it now that we can safely install Phoenix 6.

**Comment by brettle** [comment]
@ProfessorAtomicManiac Is this PR/branch still relevant? Or is everything we actually want already in 2024-beta?

**Pull request closed without merging**
